### ISSUE TITLE
Type name in page generation options is misleading

### ISSUE THREAD

**Issue by xndyz** [birkir/gatsby-source-prismic-graphql#106]
Using the proper type name in the page generation options doesn't quite work. The [plugin doesn't automatically capitalize it](https://github.com/birkir/gatsby-source-prismic-graphql/blob/master/packages/gatsby-source-prismic-graphql/src/gatsby-node.ts#L191), so you are left with this misleading error:

```
"gatsby-source-prismic-graphql" threw an error while running the createPages lifecycle:

Cannot query field "allblog_posts" on type "PRISMIC". Did you mean "allBlog_posts"?



  GraphQLError: Cannot query field "allblog_posts" on type "PRISMIC". Did you mean "allBlog_posts"?
```

I got it working by using `Blog_post` instead of `blog_post`, but this seems hacky and kind of misleading.

**Comment by Duaner** [comment]
Hey @fandy 

I understand that it might be a bit unclear because of the custom type interface in Prismic that shows the id lowercased but that is capitalized in the graphQL API.

I feel that the message is pretty explicit as is.

`Cannot query field "allblog_posts" on type "PRISMIC". Did you mean "allBlog_posts"?`

How would you improve that?
