### ISSUE TITLE
Previews Are Broken

### ISSUE THREAD

**Issue by JeffWeim** [birkir/gatsby-source-prismic-graphql#154]
I'm not sure when this issue showed up, since previews had been working for me in the `3.4.0` beta, but I am now getting this error when trying to view a preview

`Error: Network error: Error writing result to store for query:`

![Screen Shot 2020-03-10 at 3 08 53 PM](https://user-images.githubusercontent.com/8635521/76363837-13f1d180-62e1-11ea-8c6e-a9d41806ef95.png)

Is there a broken dependency?

**Comment by sebastiansson** [comment]
I think I had the same issue, fixed it in a [fork](https://github.com/Digitaliseringsbyran/gatsby-source-prismic-graphql/commit/a0e2556d140a4d4bd9ac0329a7a341f72818d3b0) for now, but I haven't tested/verified it enough to confidently create a PR. Also #143 added more issues to my setup.

The problem seems to be regarding the image query in preview mode, because gatsby-image fragments is not working when calling Prismics GraphQL API in preview mode. See this issue #139 and this PR #127 for more information.

**Comment by ffdead** [comment]
@sebastiansson I can confirm your fix solves the above problem for me. Would be nice with a PR.
Tack!

**Comment by JeffWeim** [comment]
@sebastiansson I can confirm that your fixed worked for me as well. Is there any possibility of opening a PR with your update?

**Comment by dturkington49** [comment]
We are also experiencing this issue. Is there an ETA for the fix?

**Comment by Jdruwe** [comment]
Same issue here

**Comment by sebastiansson** [comment]
Created a PR (#193), hopefully it'll get merged.

**Comment by leogilmour** [comment]
:wave: is there an ETA for this fix being published?
