### ISSUE TITLE
[Discussion]: Enable More Maintainers of the Project

### ISSUE THREAD

**Issue by JeffWeim** [birkir/gatsby-source-prismic-graphql#231]
@birkir @brandonfancher @Duaner @Decimator @arnaudlewis 

This project of late seems to be gaining more and more issues as many of the dependencies it relies on change and update around it. However, there seems to be _very_ little help from the maintainer/owner of the project to identify and work on any of the issues, merge pull request in a timely manner and, overall, perform maintenance. 

**I'm asking that access be given to more of the project's users to become active maintainers with the ability to merge and publish needed updates.** 

I had been quite happy with this project initially, however, the lack of support is rendering it useless in some cases and not allowing updates of other important dependencies in other cases.

**Comment by aodysseos** [comment]
Same here.
This is an extremely helpful plugin and I am gradeful, but it has been unreliable recently.

**Comment by ohlr** [comment]
I would also like to see more action from the Prismic team. While NuxtJS seems to get a lot of attention (https://www.slicemachine.dev/), Gatsby support seems to be rather limited.

**Comment by fitzgers** [comment]
I agree with all comments... Awesome plugin, Prismic tech support is amazingly helpful in general...  but there seems to be a blind spot here from both the Prismic side (they suggest using the plugin on their site as the default plugin) and the plugin developer side (issues not getting responded to, maintenance issues, etc...).

**Comment by greatwitenorth** [comment]
I've also been quite frustrated by the lack of development and fixes. We have had broken previews for at least 2 months now. The solution I was given by Prismic was to not use Gatsby Image. I have an active pull request to fix this issue that has yet to be responded to after 14 days. 

Prismic is a paid product and if Prismic doesn't want to actively support Gatsby then I think it's only fair that you let us know so we can choose a different direction with CMS's.

**Comment by birkir** [comment]
Wow. I am amazed at some of the comments here. This is one of the reasons why many developers stop to maintain their projects (which they do for free btw).

Prismic is by no means responsible for this plugin. They are allowed to link to different plugins on their website without having to support or contribute to it.

They are simply saying, hey here's a plugin that someone made that works quite well (at the time, or now). They are under no obligation to have to support it, but hey you know what, they kind of do and try to point you to the right direction or help in a way they can.

In my mind Prismic sells Headless CMS service not developer tools, all of the tools they build (like the toolbar, prismic-react, etc) are 100% supported and works as expected.

The company cannot support all the platforms out there, next, gatsby, nuxt, laravel, etc etc. That's why we rely on the community!

And of course, adding contributors with moderator rights is great, but nobody has asked me about it and I won't ask people of more than what they can bring. Fair? Ok.

**Comment by greatwitenorth** [comment]
@birkir Just to clarify, my frustration is not so much with your or the maintainers of this plugin but more with Prismic and the general model that they are portraying. They are in fact saying that their platform has a complete solution for use with Gatsby, and [they are pointing to this plugin](https://prismic.io/docs/reactjs/getting-started/prismic-gatsby) as that solution.

What I'd love to see is Prismic divert resources to this plugin as though it's a first class citizen of their business. Many of the other big CMS's develop their Gatsby integration in house (at least it's contained in their org's github account). I do understand that there's a fair few frameworks there. But Prismic, being a software company, requires them to be agile and adapt to technologies as they become increasingly popular and relevant. 

The work you have done here in fantastic. Just hope that Prismic could see that and provide some more help and resources. Sorry if my tone came across badly.

**Comment by ohlr** [comment]
@greatwitenorth your link is broken: I think you mean this [page](https://prismic.io/docs/gatsby/getting-started/prismic-gatsby-source-plugin) 

I try to clarify where my frustration is coming from.
Looking at the Prismic [website](https://prismic.io/docs/gatsby/getting-started/prismic-gatsby-source-plugin) I read the following
> You can easily integrate a Gatsby project with Prismic using the gatsby-source-prismic-graphql plugin.

Coming from Gatsby searching for a CMS this sounds awesome.
When looking at the repo I see that devs from prismic are actively working on issues. Awesome - official support.
Sounds like a solution that can be used in production, which I am willing to pay for.

But it turns out things aren't that great.
- Instead of "easily integrating" I am searching through Github [issues](https://github.com/birkir/gatsby-source-prismic-graphql/issues/162) to find fixes and workarounds.
- Support from prismic is rather unofficial and voluntarily. [Issues](https://github.com/birkir/gatsby-source-prismic-graphql/issues/211) which are critical for production pages are unanswered for weeks.
- I would expect that a company like prismic compensates developers that work on projects which are recommended in their marketing. Patreaon is a great way how [other](https://material-ui.com/discover-more/backers/) opensource projects get financed and maintained. @birkir I can totally understand your frustration if you're doing all this for free.

That said I still think it's the right way to go. Prismic is a nice CMS and this plugin has many advantages (Big thanks @birkir ).

**Comment by aodysseos** [comment]
Same here!

I do see your point @birkir but the frustration is with Prismic and how they make it look like they stand behind this. I made the decision to go with Prismic because of the Gatsby integration (or so it looked like) and as a paid customer I expect support over the tools they advertise.

Should they support all platforms ? No. Should they support the ones they endorse on their website? Yes, absolutely.

Obviously, this plugin is useful to lots of people and we are greatful. I think it is fair to ask support from the Prismic team over this if they are willing to say that they intergate with Gatsby.

**Comment by fitzgers** [comment]
@birkir I've chimed in earlier in this thread with my concerns/complaints, but let me reset here for a sec... You have created an AMAZING plugin for connecting Prismic/GraphQL/Gatsby, which I would wager is the most commonly used  front-end platform / querying framework combo that Prismic supports. 

You don't owe us any support, as this is an open source project, but there is a challenge for those of us who are trying to bridge the support gap between this recommended plugin and the Prismic core,  and also keep our clients happy.  We're doing our best to cover, but (speaking for myself) I just am hoping for responses from either the plugin maintainer (you) or Prismic (them) on how/who we can work with to get Previews working again.

**Comment by ohlr** [comment]
Attached a list of issues which can be closed in my (personal) opinion.
Closing such issues might help to keep focus on the important stuff.

Duplicates #218 #211
#210 
#208 
#202 
#200
#194
#176
Duplicates #165 and #87
#148
#146 
#145
#136
#134
#133
#124
#114
#110
#104
#84
#60
#44
#41
#34
#21
#20

**Comment by natedonato** [comment]
@birkir really appreciate all the work you've put into this plugin.  I think some of the confusion comes from this package being used in a bunch of official tutorials on prismic and gatsby that have gone outdated and no longer work properly out of the box following exact instructions.  Though this is a community package it is easy to mistake for an official one, and then people get frustrated when it isn't supported by a paid team of active developers.

There is an alternative fork of this that seems to be partially maintained by prismic or someone affiliated with them.  It is similar to this one but with a few extra bug fixes and patches applied.  I was able to use it and fix a couple of issues being posted here.  Anyone looking for extra support related to this plugin might want to check it out:

https://www.npmjs.com/package/@prismicio/gatsby-source-prismic-graphql

**Comment by ohlr** [comment]
The work done by [prisimic and contributors inside the fork](https://github.com/prismicio/gatsby-source-prismic-graphql) has solved my [previously raised concerns](https://github.com/birkir/gatsby-source-prismic-graphql/issues/231#issuecomment-646614633).

Finally have previews working (at least on local builds) 🎉.

**Comment by JeffWeim** [comment]
I'm closing this issue seeing how the conversation was slightly hijacked and the lack of response/understanding of what was being asked of @birkir. 

Based on what I know, if you don't want to re-write your project's sourcing plugin you should opt for a forked version of this project maintained by some folks at prismic: https://github.com/prismicio/gatsby-source-prismic-graphql

Otherwise, if you're deciding which gatsby prismic sourcing plugin to use from the onset I'd suggest this plugin: https://github.com/angeloashmore/gatsby-source-prismic
